chore: update commit-msg

diff --git a/.git-hooks/commit-msg b/.git-hooks/commit-msg
--- a/.git-hooks/commit-msg
+++ b/.git-hooks/commit-msg
@@ -3,6 +3,7 @@
 MESSAGE="$(cat $1)"
 # echo "Commit message: $MESSAGE"
 PATTERN_CONVENTIONAL_NAMING="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
+PATTERN_FOR_SCOPE="(\([a-zA-Z]+\))"
 
 if ! [[ $MESSAGE =~ ^.{0,99}$ ]]
 then
@@ -10,16 +11,14 @@ then
     exit 1
 fi
 
-if ! [[ $MESSAGE =~ ^($PATTERN_CONVENTIONAL_NAMING):.*$ ]]
+if ! [[ $MESSAGE =~ ^($PATTERN_CONVENTIONAL_NAMING):.*$ || $MESSAGE =~ ^($PATTERN_CONVENTIONAL_NAMING)$PATTERN_FOR_SCOPE:.*$ ]]
 then
-    echo "Invalid commit message. Please use conventional commit messages followeb by a colon. Example -> feat: add new feature"
+    echo "Invalid commit message. Please use conventional commit messages followeb by a colon. Example -> feat: add new feature. Other exemple -> build(deps): bump dependencies.)"
     exit 1
 fi
 
 echo "Commit message is valid."
-
 exit 0
 
 # Activate the hooks:
-# git config core.hooksPath .git-hooks
-# chmod +x ./.git-hooks/prepare-commit-msg
+# chmod +x ./.git-hooks/commit-msg
